# Generated by Django 3.1 on 2020-09-30 15:12

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=60)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='job_title')),
                ('company_name', models.CharField(default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('job_type', models.CharField(choices=[('P', 'Part Time'), ('F', 'Full Time'), ('R', 'Remote Work')], max_length=3)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('vacany', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('recruiter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['created_on'],
            },
        ),
    ]
