# Generated by Django 3.1 on 2020-10-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_remove_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Remote Work', 'Remote Work')], max_length=60),
        ),
    ]
