# Generated by Django 3.1 on 2020-10-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Jobs'},
        ),
    ]
