# Generated by Django 3.1 on 2020-10-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_auto_20201001_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
