# Generated by Django 3.0.8 on 2020-09-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('company_type', models.CharField(max_length=50)),
                ('no_emp', models.IntegerField()),
                ('privacy_policy', models.BooleanField(default=False)),
            ],
        ),
    ]
