# Generated by Django 3.0.3 on 2020-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='privacy_policy',
            field=models.BooleanField(),
        ),
    ]
