# Generated by Django 3.0.3 on 2020-09-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200917_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
