# Generated by Django 3.0.3 on 2020-09-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200917_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='privacy_policy',
        ),
    ]
