# Generated by Django 3.0.8 on 2020-09-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_recruiter_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=15)),
                ('key_skill', models.CharField(max_length=50)),
                ('industry', models.IntegerField()),
            ],
        ),
    ]
