# Generated by Django 3.0.8 on 2020-09-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20200917_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeker',
            old_name='industry',
            new_name='Industry',
        ),
    ]
