# Generated by Django 3.0.8 on 2020-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20200917_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='Industry',
        ),
        migrations.AddField(
            model_name='seeker',
            name='industry',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
