# Generated by Django 3.1.1 on 2020-09-27 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20200917_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='password',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='Industry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='linkedin',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='usernname',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='website',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
