# Generated by Django 3.1.1 on 2020-09-27 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20200927_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeker',
            old_name='industry',
            new_name='preferred_industry',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='usernname',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='linkedin',
            field=models.URLField(default=' '),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='website',
            field=models.URLField(default=' '),
        ),
    ]
